### ISSUE TITLE
ProximitySpectro search in SpectroQuery does not work

### ISSUE THREAD

**Issue by mtaghiza** [sciserver/SkyServerWS#1]
Test ID=s_spectroquery_3
When clicking on the URL, I'm getting: 
Error message:  The requested resource does not support http method 'GET'.

**Comment by raddick** [comment]
This sounds like a potentially showstopping bug? In the sense of "if this doesn't get fixed, we absolutely can't release"? Is it?

**Comment by mtaghiza** [comment]
seems that it is not a showstopping bug; turns out that ProximitySpectro is supposed to send a POST request that is not sent by just clicking that URL. Will look into another way of testing it.

**Comment by raddick** [comment]
Glad to hear it! I'll leave the Labels as-is.

Manu, since you're testing this, could you assign the issue to yourself? Just to the right here is a section that says "Assignee". Click on the gear icon and select your name.

**Comment by mtaghiza** [comment]
Had to erase erroneous [HttpPost] attribute on the get() method, which was colliding with the [HttpPost] attribute of the post() method. Now works (tested using the "postman" tool in Google chrome)

**Comment by raddick** [comment]
Confirmed as working in sciserver_v1_2_0
