### ISSUE TITLE
Use different symbols for APOGEE spectra and query matches in Finding Chart

### ISSUE THREAD

**Issue by raddick** [sciserver/SkyServerWS#17]
In the Finding Chart, we have the ability to mark objects that match some queries. These are marked in the image with upside-down purple triangles. The problem is that APOGEE spectra are also marked with upside-down triangles. The APOGEE triangles are white rather than purple, but it's not good web practice to provide information using color alone. It's confusing for all users, but deal-breaking for colorblind users.

We should choose a different symbol for marking the query matches.

**Comment by raddick** [comment]
Update: @deoyani  is working on this in her branch of the code in her dev space. See

http://scidev03.pha.jhu.edu/skyserverws-deo/DR12/ImgCutout/getjpeg?ra=132.749&dec=11.656&scale=0.7&width=512&height=512&opt=A

Thanks Deoyani!

**Comment by mtaghiza** [comment]
Seems that Deoyani fixed this already.

**Comment by mtaghiza** [comment]
Yellow diamonds are marked on top of apogee objects. Tested on version 1.8.1. Closing...
