### ISSUE TITLE
Targets do not show

### ISSUE THREAD

**Issue by raddick** [sciserver/SkyServerWS#18]
In doing test s_img_10 , I added "A" as an optional parameter to the ImgCutout web services URL. Symbols for targets do not show. But maybe it is expected for them not to show? Check with @thakar . Filing this as a bug for now; we can maybe change to invalid if it turns out to be the expected behavior.

**Comment by thakar** [comment]
You mean Apogee spectra?  They do show at a different location (e.g. the
default one for the production SkyServer), see attached screenshot.

```
    Ani
```

## 

Aniruddha R. Thakar, Principal Research Scientist
Center for Astrophysical Sciences and
Institute for Data Intensive Engineering & Science (IDIES), JHU
3701 San Martin Drive, Baltimore MD 21218-2695
410-516-4850, thakar@jhu.edu,  www.sdss.jhu.edu/~thakar

## http://www.sdss.jhu.edu/%7Ethakar

The freedoms that we exercise but do not acknowledge are easily
taken away. [Barbara Ehrenreich]

**Comment by raddick** [comment]
No, I mean the spetroscopic targets from SDSS-I through SDSS-III. We 
showed these at one point in the past, I think as Xs. Not sure what 
happened to them.

**Comment by thakar** [comment]
We've never had those in SDSS-III, because we don't have targeting info for
non-SDSS targets anyway (BOSS etc.).

```
      Ani
```

## 

Aniruddha R. Thakar, Principal Research Scientist
Center for Astrophysical Sciences and
Institute for Data Intensive Engineering & Science (IDIES), JHU
3701 San Martin Drive, Baltimore MD 21218-2695
410-516-4850, thakar@jhu.edu,  www.sdss.jhu.edu/~thakar

## http://www.sdss.jhu.edu/%7Ethakar

The freedoms that we exercise but do not acknowledge are easily
taken away. [Barbara Ehrenreich]

**Comment by raddick** [comment]
So should we remove the option in the Navigate tool?

**Comment by thakar** [comment]
Remove from where? It's not listed in the Drawing Options.  BTW, the A
option (APOGEE spectra) is not listed in the drawing options documentation,
it should be added.

```
   Ani
```

## 

Aniruddha R. Thakar, Principal Research Scientist
Center for Astrophysical Sciences and
Institute for Data Intensive Engineering & Science (IDIES), JHU
3701 San Martin Drive, Baltimore MD 21218-2695
410-516-4850, thakar@jhu.edu,  www.sdss.jhu.edu/~thakar

## http://www.sdss.jhu.edu/%7Ethakar

Do all the good you can. By all the means you can. In all the ways
you can.  In all the places you can. At all the times you can. To
all the people you can. As long as ever you can. [John Wesley]

**Comment by raddick** [comment]
This is working correctly, so closing. This has become a documentation issue, filed as #20 .

**Comment by raddick** [comment]
Remove from the documentation, both on the web services site and on the 
SkyServer site. This has now become a documentation issue, so I'll file 
it as such in both SkyServerWS and SkyServer, and self-assign.
