### ISSUE TITLE
Add "&format=json" to service call URL on Cone Search test spreadsheet (and maybe other sheets?)

### ISSUE THREAD

**Issue by raddick** [sciserver/SkyServerWS#19]
The test script specifies tests of the cone search web service to work through URLs like this:

http://scitest02.pha.jhu.edu/skyserverws/dr12/ConeSearch/ConeSearchService?ra=145&dec=34&sr=1

Pasting that link results in a blank page for me. I've tried in several browsers on both Mac and PC.

**Comment by raddick** [comment]
Figured it out. Actually, the service is working, I just needed to add

&format=json

to the end of the service call URL.

So this is a fixtestscript issue; updating as such.

**Comment by mtaghiza** [comment]
Closing...
