### ISSUE TITLE
Rectangular Search breaks when adding apparent magnitude constraint

### ISSUE THREAD

**Issue by mtaghiza** [sciserver/SkyServerWS#2]
Test ID: s_newrect_1

The Rectangular Search breaks after adding the parameter &uband=0,15 in the url. 

Error:

{"Error Code":500,"Error Type":"InternalServerError","Error Message":"Failed to execute a query: Invalid column name 'u'.\r\nInvalid column name 'u'.","LogMessageID":"9acede03-ff9c-485e-8057-97cc4ea0b46b"}

**Comment by mtaghiza** [comment]
The problem was that the constraint was enforced in the apogee tables as well, where there is no u magnitude. Have to eliminate visible-band magnitude constraints on infrared data.

**Comment by raddick** [comment]
Confirmed as working in sciserver_v1_2_0
