### ISSUE TITLE
"Equatorial" misspelled in either test script or in service parameters

### ISSUE THREAD

**Issue by raddick** [sciserver/SkyServerWS#25]
I hate this word, and I constantly misspell it. The correct spelling is "equatorial" , with an a like "equator".

In the testing script, the service URLs are shown with that evil word misspelled. I'm not sure if the misspelling is found in the test script, or if the parameter that the service is expecting is misspelled.

If the misspelling is in the test script, it's an easy fix.

If the misspelling is in the service call, how important is it that the service call parameters be human-readable?

Tagging this as a question.

**Comment by mtaghiza** [comment]
fixed. All entries in the web page and web-service were changed to equatorial.

**Comment by mtaghiza** [comment]
Closing...
