### ISSUE TITLE
SQL Search: HTML doesn't render as HTML

### ISSUE THREAD

**Issue by raddick** [sciserver/SkyServerWS#26]
I'm actually not sure whether this is even a bug, or whether this is just expected behavior. Filing it as both bug and question. Feel free to mark as invalid if this is just the way it's supposed to work.

When I submit a query using the SQL Search web service and request HTML as the format, it shows the HTML as plaintext with tags rather than rendering the HTML. Screenshot below.

<img width="973" alt="untitled-1" src="https://cloud.githubusercontent.com/assets/1709156/10798355/98737d4e-7d7d-11e5-9f38-180c2ebce2e5.png">

**Comment by mtaghiza** [comment]
This is the way it is supposed to work (skyserver has no problem displaying the page), but it would be nice to display it immediately as a webpage. Will check this later.

**Comment by mtaghiza** [comment]
Fixed.

**Comment by mtaghiza** [comment]
Rendering now nice html pages. test version 1.8.1. Closing
