### ISSUE TITLE
Should there be an index page?

### ISSUE THREAD

**Issue by raddick** [sciserver/SkyServerWS#27]
If you go to the top-level directory with this URL:

http://scitest02.pha.jhu.edu/SkyserverWS/

You get a "The resource could not be found" message.

Should there be an index page there describing what web services are available? I remember there was such a page on the version on Deoyani's machine.

**Comment by mtaghiza** [comment]
You can use  http://scitest02.pha.jhu.edu/SkyserverWS/default.aspx
This page has to be updated, though.
