### ISSUE TITLE
Test the "New Rectangular" search?

### ISSUE THREAD

**Issue by raddick** [sciserver/SkyServerWS#29]
There is a sheet in the test spreadsheet called "SkyServerWS-NewRectangular". It gives a URL of:

http://scitest02.pha.jhu.edu/SkyserverWS/dr12SearchTools/

but there's nothing there.

Is there supposed to be a service there we should test? Or do we need to remove this sheet from the testing spreadsheet?

**Comment by mtaghiza** [comment]
Not heard of that service. Please remove the sheet if there are no test steps specified in there.

**Comment by mtaghiza** [comment]
Closing...
