### ISSUE TITLE
Radial Search breaks when adding apparent magnitude constraint

### ISSUE THREAD

**Issue by mtaghiza** [sciserver/SkyServerWS#3]
Test ID: s_radial_1

The Radial Search breaks after adding the parameter &uband=0,15 in the url.
Throws errors with constraints on other SDSS filters as well.

Error:

{"Error Code":500,"Error Type":"InternalServerError","Error Message":"Failed to execute a query: Invalid column name 'u'.\r\nInvalid column name 'u'.","LogMessageID":"7620d5e9-ff2e-4550-9d4a-19966c99d85a"}

**Comment by mtaghiza** [comment]
The problem was that the constraint was enforced in the apogee tables as well, where there is no u magnitude. Have to eliminate visible-band magnitude constraints on infrared data.

**Comment by raddick** [comment]
Confirmed as working in sciserver_v1_2_0
