### ISSUE TITLE
IR Spec Search WS: Which takes priority, RA/dec or L/B?

### ISSUE THREAD

**Issue by raddick** [sciserver/SkyServerWS#30]
If the URL contains both a value of (ra,dec) and (Lcenter,Bcenter), which gets priority? Which search will be executed, and results shown to the user?

It looks like (ra,dec) takes priority; please confirm or deny. This will need to be documented in both the service documentation and the test script.

**Comment by mtaghiza** [comment]
This issue was discussed in #11 , please close this one.
