### ISSUE TITLE
ImgCutout does not mark objects with spectra with squares

### ISSUE THREAD

**Issue by mtaghiza** [sciserver/SkyServerWS#4]
The ?opt=S option is currently not using squares to mark objects with spectra.

**Comment by mtaghiza** [comment]
Now it works. Caused by a change of the schema in the views. The view 'specobj' was giving the wrong values for 'ra' and 'cx', making the finding of the objects impossible. All the views were recreated, and now it works.

**Comment by raddick** [comment]
Confirmed as working in sciserver_v1_2_0
