### ISSUE TITLE
ImgCutout does not mark objects with after specifying options "S" or "T"

### ISSUE THREAD

**Issue by mtaghiza** [sciserver/SkyServerWS#5]
Tests s_img_9 and s_img_10
Links:

http://scitest02.pha.jhu.edu/SkyserverWS/dr12/ImgCutout/getjpeg?ra=197.614&dec=18.438&scale=0.7&width=512&height=512&opt=S

and 
http://scitest02.pha.jhu.edu/SkyserverWS/dr12/ImgCutout/getjpeg?ra=197.614&dec=18.438&scale=0.7&width=512&height=512&opt=T

**Comment by mtaghiza** [comment]
Caused by a change of the schema in the views. The view 'specobj' was giving the wrong values for 'ra' and 'cx', making the finding of the objects impossible. All the views where recreated, and now it works. 

The T option (mark targeted objects) is no longer available, since the table 'Target' no longer exists in the schema (or at least its rows are not populated).

**Comment by raddick** [comment]
Confirmed as working in sciserver_v1_2_0
